### ISSUE TITLE
Add a testsuite

### ISSUE THREAD

**Issue by ninsbl** [HamedElgizery/grass-addons#5]
After a first experimental version is merged, a testsuite should be added, either as unittests, doctests, pytest (or both).
If no credentials are needed for searching, that can be part of a unittest without any need to admin access to the _grass-addons_ repo...

You can get inspiration from unittests in other addons...

**Comment by veroandreo** [comment]
> no credentials are needed for searching

is this true for all providers or only some of them? Perhaps this is a note worth adding to the i.eodag manual page

**Comment by HamedElgizery** [comment]
> > no credentials are needed for searching
> 
> is this true for all providers or only some of them? Perhaps this is a note worth adding to the i.eodag manual page

Only some of the providers allow searching without credentials...
I guess we could pick some of them, and add a unittest for searching without credentials with these.
