### ISSUE TITLE
Allow to have a file as input for ids to download

### ISSUE THREAD

**Issue by ninsbl** [HamedElgizery/grass-addons#6]
It is possible, that users may want to download a lager number of files by ID.
Therefore, we should consider also the possibility of "file" input to the `id` option.

**Comment by HamedElgizery** [comment]
Do you mean by that we can have a TXT file with a list of IDs (separated by commas maybe), and then we could pass that file to the id option, and then download them?

Also, I think it is relevant to mention this here... there is this serialization/deserialization methods provided by eodag, to save the search results as a GeoJSON file. I will add support for that as well.
https://eodag.readthedocs.io/en/stable/notebooks/api_user_guide/5_serialize_deserialize.html

Would it be reasonable to consider other file types... like CSV? Is it typically used in GRASS?

**Comment by ninsbl** [comment]
A text file with one ID per line would be good. 

The EODAG produced GeoJSON makes sense too, but plain text seems more simple, esp. if users identify IDs by other means...

**Comment by HamedElgizery** [comment]
Added the text file with IDs option here #8

**Comment by veroandreo** [comment]
The module could also attempt to download all items found by default, unless an id or a list (or file of) ids is passed, IIRC this was the behavior of i.landsat.download

**Comment by HamedElgizery** [comment]
Merged to trunk. https://github.com/OSGeo/grass-addons/pull/1097
